version: '2'

services:
  jupyterlab:
    build: .
    command: "bash -c 'jupyter lab --no-browser --ip=* --port=9000 --allow-root --notebook-dir=/project/notebooks --NotebookApp.token=\"\"'"
    volumes:
      - ./:/project
    ports:
      - 9000:9000